require 'treat'
require 'json'
require_relative './prosody/graph'
require_relative './prosody/poem'
require_relative './prosody/cmudict_parser'
require_relative './prosody/type'
require_relative './prosody/rhyme'
